# Generated by Django 3.2.5 on 2021-07-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pictures/profilepic.png', upload_to='pictures/profile_pictures'),
        ),
    ]
